// <auto-generated />
using System;
using CrunchyPeanutButter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrunchyPeanutButter.Infrastructure.Migrations
{
    [DbContext(typeof(CrunchyPeanutButterDbContext))]
    partial class CrunchyPeanutButterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarFoo", b =>
                {
                    b.Property<Guid>("BarsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BarsId", "FoosId");

                    b.HasIndex("FoosId");

                    b.ToTable("BarFoo");
                });

            modelBuilder.Entity("CrunchyPeanutButter.Core.Models.Bars.Ack", b =>
                {
                    b.Property<Guid>("BarId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BarId");

                    b.ToTable("Ack");
                });

            modelBuilder.Entity("CrunchyPeanutButter.Core.Models.Bars.Bar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("CrunchyPeanutButter.Core.Models.Foos.Baz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FooId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooId");

                    b.ToTable("Baz");
                });

            modelBuilder.Entity("CrunchyPeanutButter.Core.Models.Foos.Foo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foos");
                });

            modelBuilder.Entity("BarFoo", b =>
                {
                    b.HasOne("CrunchyPeanutButter.Core.Models.Bars.Bar", null)
                        .WithMany()
                        .HasForeignKey("BarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrunchyPeanutButter.Core.Models.Foos.Foo", null)
                        .WithMany()
                        .HasForeignKey("FoosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrunchyPeanutButter.Core.Models.Bars.Ack", b =>
                {
                    b.HasOne("CrunchyPeanutButter.Core.Models.Bars.Bar", "Bar")
                        .WithOne("Ack")
                        .HasForeignKey("CrunchyPeanutButter.Core.Models.Bars.Ack", "BarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bar");
                });

            modelBuilder.Entity("CrunchyPeanutButter.Core.Models.Foos.Baz", b =>
                {
                    b.HasOne("CrunchyPeanutButter.Core.Models.Foos.Foo", "Foo")
                        .WithMany("Bazs")
                        .HasForeignKey("FooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foo");
                });

            modelBuilder.Entity("CrunchyPeanutButter.Core.Models.Bars.Bar", b =>
                {
                    b.Navigation("Ack");
                });

            modelBuilder.Entity("CrunchyPeanutButter.Core.Models.Foos.Foo", b =>
                {
                    b.Navigation("Bazs");
                });
#pragma warning restore 612, 618
        }
    }
}
